/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/Boardgames": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["BoardgameCreateDto"];
          "text/json": components["schemas"]["BoardgameCreateDto"];
          "application/*+json": components["schemas"]["BoardgameCreateDto"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Boardgames/{id}": {
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["BoardgameUpdateDto"];
          "text/json": components["schemas"]["BoardgameUpdateDto"];
          "application/*+json": components["schemas"]["BoardgameUpdateDto"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/GameEvents": {
    get: {
      parameters: {
        query?: {
          q?: string;
          gameId?: number;
          ownerUserId?: string;
          from?: string;
          to?: string;
          upcomingOnly?: boolean;
          pastOnly?: boolean;
          minPlayers?: number;
          maxPlayers?: number;
          hasAvailableSlots?: boolean;
          sortBy?: string;
          sortDir?: string;
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateGameEventDto"];
          "text/json": components["schemas"]["UpdateGameEventDto"];
          "application/*+json": components["schemas"]["UpdateGameEventDto"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateGameEventDto"];
          "text/json": components["schemas"]["CreateGameEventDto"];
          "application/*+json": components["schemas"]["CreateGameEventDto"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/GameEvents/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        query?: {
          ownerUserId?: string;
        };
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Items": {
    get: {
      parameters: {
        query?: {
          q?: string;
          type?: string;
          category?: string;
          sortBy?: string;
          sortDir?: string;
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Items/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Videogames": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["VideogameCreateDto"];
          "text/json": components["schemas"]["VideogameCreateDto"];
          "application/*+json": components["schemas"]["VideogameCreateDto"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Videogames/{id}": {
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["VideogameUpdateDto"];
          "text/json": components["schemas"]["VideogameUpdateDto"];
          "application/*+json": components["schemas"]["VideogameUpdateDto"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/WeatherForecast": {
    get: operations["GetWeatherForecast"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    BoardgameCreateDto: {
      item?: components["schemas"]["ItemBaseCreateDto"];
      /** Format: int32 */
      minPlayers?: number;
      /** Format: int32 */
      maxPlayers?: number;
      /** Format: int32 */
      bggId?: number | null;
      /** Format: double */
      bggRating?: number | null;
      /** Format: double */
      bggAverageRating?: number | null;
      /** Format: int32 */
      bggRank?: number | null;
      /** Format: int32 */
      learnDifficulty?: number | null;
      /** Format: int32 */
      playDifficulty?: number | null;
    };
    BoardgameUpdateDto: {
      item?: components["schemas"]["ItemBaseUpdateDto"];
      /** Format: int32 */
      minPlayers?: number;
      /** Format: int32 */
      maxPlayers?: number;
      /** Format: int32 */
      bggId?: number | null;
      /** Format: double */
      bggRating?: number | null;
      /** Format: double */
      bggAverageRating?: number | null;
      /** Format: int32 */
      bggRank?: number | null;
      /** Format: int32 */
      learnDifficulty?: number | null;
      /** Format: int32 */
      playDifficulty?: number | null;
    };
    CreateGameEventDto: {
      /** Format: int32 */
      id?: number;
      /** Format: int32 */
      gameId?: number;
      /** Format: date-time */
      startTime?: string;
      /** Format: date-time */
      endTime?: string;
      /** Format: int32 */
      minNumberOfPlayers?: number | null;
      /** Format: int32 */
      maxNumberOfPlayers?: number | null;
      ownerUserId?: string | null;
    };
    ItemBaseCreateDto: {
      name?: string | null;
      /** Format: int32 */
      length?: number | null;
      description?: string | null;
      thumbnail?: string | null;
      /** Format: int32 */
      copies?: number | null;
      categories?: string[] | null;
    };
    ItemBaseUpdateDto: {
      name?: string | null;
      /** Format: int32 */
      length?: number | null;
      description?: string | null;
      thumbnail?: string | null;
      /** Format: int32 */
      copies?: number | null;
      categories?: string[] | null;
    };
    UpdateGameEventDto: {
      /** Format: uuid */
      gameEventId?: string;
      /** Format: int32 */
      gameId?: number;
      /** Format: date-time */
      startTime?: string;
      /** Format: date-time */
      endTime?: string;
      /** Format: int32 */
      minNumberOfPlayers?: number | null;
      /** Format: int32 */
      maxNumberOfPlayers?: number | null;
      ownerUserId?: string | null;
    };
    VideogameCreateDto: {
      item?: components["schemas"]["ItemBaseCreateDto"];
      /** Format: int32 */
      minPlayers?: number;
      /** Format: int32 */
      maxPlayers?: number;
      /** Format: int32 */
      playingTime?: number;
      /** Format: int32 */
      difficulty?: number | null;
      /** Format: int32 */
      platform?: number | null;
    };
    VideogameUpdateDto: {
      item?: components["schemas"]["ItemBaseUpdateDto"];
      /** Format: int32 */
      minPlayers?: number;
      /** Format: int32 */
      maxPlayers?: number;
      /** Format: int32 */
      playingTime?: number;
      /** Format: int32 */
      difficulty?: number | null;
      /** Format: int32 */
      platform?: number | null;
    };
    WeatherForecast: {
      /** Format: date */
      date?: string;
      /** Format: int32 */
      temperatureC?: number;
      /** Format: int32 */
      temperatureF?: number;
      summary?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  GetWeatherForecast: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "text/plain": components["schemas"]["WeatherForecast"][];
          "application/json": components["schemas"]["WeatherForecast"][];
          "text/json": components["schemas"]["WeatherForecast"][];
        };
      };
    };
  };
}
